# Default values for helm_deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: ""
  repository: ""
  tag: ""
  pullPolicy: Always

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: [ "ALL" ]
  seccompProfile:
    type:
      RuntimeDefault
  runAsNonRoot: true
  readOnlyRootFilesystem: false
  runAsUser: 1001

service:
  type: ClusterIP
  port: 8085
  environment: ""

actuator:
  port: 8185
  metrics:
    scrapeInterval: 15s
    path: /actuator/prometheus
  health:
    path: /actuator/health
  liveness:
    initialDelaySeconds: 45
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 5
  readiness:
    initialDelaySeconds: 45
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 5

ingress:
  className: "modsec"
  annotations:
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "300"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
      SecDefaultAction "phase:2,pass,log,tag:github_team=laa-fee-scheme"
    # This settings will restrict access by IP to MoJ users only
    nginx.ingress.kubernetes.io/whitelist-source-range: 51.149.249.0/29,194.33.249.0/29,51.149.249.32/29,194.33.248.0/29,20.49.214.199/32,20.49.214.228/32,20.26.11.71/32,20.26.11.108/32,128.77.75.64/26,18.169.147.172/32,35.176.93.186/32,18.130.148.126/32,35.176.148.126/32,35.178.209.113/32,3.8.51.207/32,35.177.252.54/32
    nginx.ingress.kubernetes.io/server-snippet: |
      location @custom_403 {
        return 403 "<html> <head> <meta http-equiv='Content-Type' content='text/html; charset=UTF-8'></head><body> <div class='container'> <div class='content'> <div class='title'>You are not authorised to access this application</div><div><br><br><b><a href='mailto:LAA-Fee-Scheme-Platform@justice.gov.uk?subject=Access%20support%20request%20Fee%20Scheme%20Platform' target='_top'>Contact Us</a></b> if you have any queries</div></div></div></body></html>";
      }
      error_page 403 @custom_403;
  hosts: []

  tls: []

resources: {}

autoscaling:
  enabled: false

sentry:
  enabled: false