services:
  app:
    build:
      context: .
    ports:
      - "8085:8085"
      - "8185:8185"
    environment:
        - DB_SERVER=postgres
        - DB_NAME=fee_scheme_test_db
        - DB_USER=dev
        - DB_PASSWORD=dev
        - DATA_CLAIMS_EVENT_SERVICE_TOKEN=1234
        - SENTRY_DSN=
    depends_on:
      postgres:
        condition: service_started

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  # Local Postgres database service
  postgres:
    container_name: fee-scheme-db
    image: postgres:17
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: fee_scheme_test_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data: