services:
  app:
    build:
      context: .
    ports:
      - "8085:8085"
      - "8185:8185"
#    environment:
#        - DB_SERVER=postgres
#        - DB_NAME=fee_scheme_test_db
#        - DB_USER= # enter chosen DB user here
#        - DB_PASSWORD= # enter chosen DB password here
#    depends_on:
#      postgres:
#        condition: service_started

  # Local Postgres database service
  postgres:
    container_name: fee-scheme-db
    image: postgres
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: fee_scheme_test_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data: