apiVersion: apps/v1
kind: Deployment
metadata:
  name: laa-fee-scheme-api-deployment
  namespace: ${NAMESPACE}
  labels:
    app: laa-fee-scheme-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laa-fee-scheme-api # this should match the selector in service.yml
  template:
    metadata:
      labels:
        app: laa-fee-scheme-api # this should match the selector in service.yml
    spec:
      containers:
        - name: laa-fee-scheme-api
          image: ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}
          ports:
            - containerPort: 8085
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ "ALL" ]
            seccompProfile:
              type: RuntimeDefault
            runAsNonRoot: true
            runAsUser: 1001
          env:
            - name: DB_SERVER
              valueFrom:
                secretKeyRef:
                  name: rds-postgresql-instance-output
                  key: rds_instance_endpoint
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: rds-postgresql-instance-output
                  key: database_name
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: rds-postgresql-instance-output
                  key: database_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rds-postgresql-instance-output
                  key: database_password