package uk.gov.justice.laa.fee.scheme.enums;

/**
 * Enum for the types of category of law.
 */
public enum CategoryType {
  ADVOCACY_APPEALS_REVIEWS,
  ASSOCIATED_CIVIL,
  CLAIMS_PUBLIC_AUTHORITIES,
  CLINICAL_NEGLIGENCE,
  COMMUNITY_CARE,
  DEBT,
  DISCRIMINATION,
  EDUCATION,
  FAMILY,
  HOUSING,
  HOUSING_HLPAS,
  IMMIGRATION_ASYLUM,
  MAGS_COURT_DESIGNATED,
  MAGS_COURT_UNDESIGNATED,
  MEDIATION,
  MENTAL_HEALTH,
  MISCELLANEOUS,
  POLICE_STATION,
  PUBLIC_LAW,
  PRISON_LAW,
  WELFARE_BENEFITS,
  YOUTH_COURT_DESIGNATED,
  YOUTH_COURT_UNDESIGNATED,
}
