openapi: "3.0.0"
info:
  version: 1.0.0
  title: Fee Scheme API
paths:
  /api/v1/category-of-law/{feeCode}:
    get:
      tags:
        - categoryOfLaw
      parameters:
        - name: feeCode
          in: path
          required: true
          description: Fee Code to retrieve Category of Law
          schema:
            type: string
      summary: Get Category of Law
      operationId: getCategoryOfLaw
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CategoryOfLaw"
        '400':
          description: 'Bad request'
        '401':
          description: 'Unauthorized'
        '403':
          description: 'Forbidden'
        '404':
          description: 'Not found'
        '500':
          description: 'Internal server error'
components:
  schemas:
    CategoryOfLaw:
      required:
        - categoryOfLawCode
      properties:
        categoryOfLawCode:
          type: string
