openapi: "3.0.0"
info:
  version: 1.0.0
  title: Fee Scheme API
paths:
  /api/v1/fee-details/{feeCode}:
    get:
      tags:
        - feeDetails
      parameters:
        - name: feeCode
          in: path
          required: true
          description: Fee Code to retrieve Category of Law
          schema:
            type: string
      summary: Get Category of Law and Fee details
      operationId: getFeeDetails
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FeeDetailsResponse"
        '400':
          description: 'Bad request'
        '401':
          description: 'Unauthorized'
        '403':
          description: 'Forbidden'
        '404':
          description: 'Category code not found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: 'Internal server error'

  /api/v1/fee-calculation:
    post:
      tags:
        - feeCalculation
      summary: Post fee data for calculating fee total
      operationId: getFeeCalculation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FeeCalculationRequest"
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FeeCalculationResponse"
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not found
        '500':
          description: Internal server error

components:
  schemas:
    FeeDetailsResponse:
      required:
        - categoryOfLawCode
      properties:
        categoryOfLawCode:
          type: string
          description: "Category of law corresponding to fee code"
        feeCodeDescription:
          type: string
          description: "Description of fee code"
        feeType:
          type: string
          description: "Type of fee, Fixed, Hourly, disbursement only"

    FeeCalculationRequest:
      type: object
      required:
        - feeCode
        - vatIndicator
      properties:
        feeCode:
          type: string
          description: "Fee code corresponding to a category of law."
        claimId:
          type: string
          description: "Unique identifier for a Claim record."
        startDate:
          type: string
          format: date
          description: "Civil: case start date."
        policeStationId:
          type: string
          description: "Police Station ID."
        policeStationSchemeId:
          type: string
          description: "Police Station Scheme ID."
        uniqueFileNumber:
          type: string
          description: "Unique File Number (UFN) for Police Station/Prison Law category. Format DDMMYY/NNNN"
        netProfitCosts:
          type: number
          format: double
          description: "Used for hourly Fee calculation."
        netCostOfCounsel:
          type: number
          format: double
          description: "Value of cost of counsel."
        netDisbursementAmount:
          type: number
          format: double
          description: "Value of disbursement requested."
        disbursementVatAmount:
          type: number
          format: double
          description: "Vat Value of disbursement."
        vatIndicator:
          type: boolean
          description: "Indicates if VAT should be applied to Fee calculation."
        boltOns:
          $ref: "#/components/schemas/BoltOnType"
        netTravelCosts:
          type: number
          format: double
          description: "Value of travel costs."
        netWaitingCosts:
          type: number
          format: double
          description: "Value of waiting costs."
        travelAndWaitingCosts:
          type: number
          format: double
          description: "Value of travel and waiting."
        detentionTravelAndWaitingCosts:
          type: number
          format: double
          description: "Value of detention travel and waiting costs costs"
        caseConcludedDate:
          type: string
          format: date
        policeCourtOrPrisonId:
          type: string
          description: "ID corresponding with police, court or prison."
        schemeId:
          type: string
          description: "Scheme Id for police station fixed fee calculation."
        numberOfMediationSessions:
          type: integer
          description: "Number of mediation sessions, where applicable this will determine fixed fee for mediation category of law."
        jrFormFilling:
          type: number
          format: double
          description: "Value of form filling."
        immigrationPriorAuthorityNumber:
          type: string
          description: "Authorisation specific to immigration, used for net profit costs over limit or disbursements over limit."
        representationOrderDate:
          type: string
          format: date
          description: "The official start date for claimable work carried out for Crime Lower categories"
        londonRate:
          type: boolean
          description: "Indicates if London rate is applied otherwise Non London rate is applied."

    FeeCalculationResponse:
      type: object
      properties:
        feeCode:
          type: string
          description: "Fee code that was supplied via request."
        schemeId:
          type: string
          description: "Scheme ID that was used for calculation."
        claimId:
          type: string
          description: "Unique identifier for a Claim record."
        validationMessages:
          $ref: "#/components/schemas/ValidationMessages"
        escapeCaseFlag:
          type: boolean
          description: "For hourly fee code, If escape threshold has been passed, will be true, false otherwise."
        feeCalculation:
          $ref: "#/components/schemas/FeeCalculation"

    FeeCalculation:
      type: object
      properties:
        totalAmount:
          type: number
          format: double
          description: "The total fee amount that has been calculated."
        vatIndicator:
          type: boolean
          description: "Whether Vat was requested to be added onto calculation (excluding disbursement)."
        vatRateApplied:
          type: number
          format: double
          description: "The Vat rate that was used in calculation."
        calculatedVatAmount:
          type: number
          format: double
          description: "Total amount of Vat that was calculated (excluding disbursement)."
        disbursementAmount:
          type: number
          format: double
          description: "The disbursement amount calculated to be added."
        requestedNetDisbursementAmount:
          type: number
          format: double
          description: "The disbursement amount that was requested."
        disbursementVatAmount:
          type: number
          format: double
          description: "The disbursement Vat amount calculated to be added."
        hourlyTotalAmount:
          type: number
          format: double
          description: "Hourly total amount calculated."
        fixedFeeAmount:
          type: number
          format: double
          description: "Fixed Fee amount calculated."
        netProfitCostsAmount:
          type: number
          format: double
          description: "The net profit cost amount calculated to be added."
        requestedNetProfitCostsAmount:
          type: number
          format: double
          description: "The profit cost amount requested."
        netCostOfCounselAmount:
          type: number
          format: double
          description: "The cost of counsel requested."
        netTravelCostsAmount:
          type: number
          format: double
          description: "The net travel cost requested."
        netWaitingCostsAmount:
          type: number
          format: double
          description: "The net waiting cost requested."
        detentionTravelAndWaitingCostsAmount:
          type: number
          format: double
          description: "The detention travel and waiting costs requested."
        jrFormFillingAmount:
          type: number
          format: double
          description: "The Jr form filling costs requested."
        travelAndWaitingCostAmount:
          type: number
          format: double
          description: "The Travel and waiting costs requested."
        boltOnFeeDetails:
          $ref: "#/components/schemas/BoltOnFeeDetails"

    ValidationMessages:
      type: array
      items:
        type: object
        properties:
          type:
            type: string
            enum: [ERROR, WARNING]
          message:
            type: string

    BoltOnFeeDetails:
      type: object
      properties:
        boltOnTotalFeeAmount:
          type: number
          format: double
        boltOnAdjournedHearingCount:
          type: integer
        boltOnAdjournedHearingFee:
          type: number
          format: double
        boltOnCmrhTelephoneCount:
          type: integer
        boltOnCmrhTelephoneFee:
          type: number
          format: double
        boltOnCmrhOralCount:
          type: integer
        boltOnCmrhOralFee:
          type: number
          format: double
        boltOnHomeOfficeInterviewCount:
          type: integer
        boltOnHomeOfficeInterviewFee:
          type: number
          format: double

    BoltOnType:
      type: object
      properties:
        boltOnAdjournedHearing:
          type: integer
        boltOnCmrhOral:
          type: integer
        boltOnCmrhTelephone:
          type: integer
        boltOnHomeOfficeInterview:
          type: integer

    ErrorResponse:
      type: object
      description: Standard error response returned for failed requests
      properties:
        timestamp:
          type: string
          format: date-time
          description: Time when the error occurred
          example: "2025-09-08T13:15:30"
        status:
          type: integer
          description: HTTP status code associated with the error
          example: 404
        error:
          type: string
          description: Description of the HTTP error
          example: "Not Found"
        message:
          type: string
          description: Description/explanation of the error
          example: "Category code not found for fee code: X123"