openapi: "3.0.0"
info:
  version: 1.0.0
  title: Fee Scheme API
paths:
  /api/v1/category-of-law/{feeCode}:
    get:
      tags:
        - categoryOfLaw
      parameters:
        - name: feeCode
          in: path
          required: true
          description: Fee Code to retrieve Category of Law
          schema:
            type: string
      summary: Get Category of Law
      operationId: getCategoryOfLaw
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CategoryOfLawResponse"
        '400':
          description: 'Bad request'
        '401':
          description: 'Unauthorized'
        '403':
          description: 'Forbidden'
        '404':
          description: 'Category code not found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: 'Internal server error'

  /api/v1/fee-calculation:
    post:
      tags:
        - feeCalculation
      summary: Post fee data for calculating fee total
      operationId: getFeeCalculation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FeeCalculationRequest"
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FeeCalculationResponse"
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not found
        '500':
          description: Internal server error

components:
  schemas:
    CategoryOfLawResponse:
      required:
        - categoryOfLawCode
      properties:
        categoryOfLawCode:
          type: string

    FeeCalculationRequest:
      type: object
      required:
        - feeCode
      properties:
        feeCode:
          type: string
        startDate:
          type: string
          format: date
          description: "Civil: case start date. Crime: Representation order date."
        netProfitCosts:
          type: number
          format: double
        netDisbursementAmount:
          type: number
          format: double
        netCostOfCounsel:
          type: number
          format: double
        disbursementVatAmount:
          type: number
          format: double
        vatIndicator:
          type: boolean
        disbursementPriorAuthority:
          type: string
        boltOns:
          $ref: "#/components/schemas/BoltOnType"
        netTravelCosts:
          type: number
          format: double
        netWaitingCosts:
          type: number
          format: double
        caseConcludedDate:
          type: string
          format: date
        policeCourtOrPrisonId:
          type: string
        dutySolicitor:
          type: string
        schemeId:
          type: string
        ufn:
          type: string
        numberOfMediationSessions:
          type: integer

    FeeCalculationResponse:
      type: object
      properties:
        feeCode:
          type: string
        feeCalculation:
          $ref: "#/components/schemas/FeeCalculation"

    FeeCalculation:
      type: object
      properties:
        totalAmount:
          type: number
          format: double
        subTotal:
          type: number
          format: double

    BoltOnType:
      type: object
      properties:
        boltOnAdjournedHearing:
          type: integer
        boltOnDetentionTravelWaitingCosts:
          type: integer
        boltOnJrFormFilling:
          type: integer
        boltOnCmrhOral:
          type: integer
        boltOnCrmhTelephone:
          type: integer
        boltOnAdditionalTravel:
          type: integer

    ErrorResponse:
      type: object
      description: Standard error response returned for failed requests
      properties:
        timestamp:
          type: string
          format: date-time
          description: Time when the error occurred
          example: "2025-09-08T13:15:30"
        status:
          type: integer
          description: HTTP status code associated with the error
          example: 404
        error:
          type: string
          description: Description of the HTTP error
          example: "Not Found"
        message:
          type: string
          description: Description/explanation of the error
          example: "Category code not found for fee code: X123"