server:
  port: 8085

spring:
  application:
    name: LAA Fee Scheme API

  datasource:
    url: 'jdbc:postgresql://${DB_SERVER}/${DB_NAME}'
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      pool-name: fee-scheme-DB-CP
      connection-timeout: 1000
      validation-timeout: 500
      maximum-pool-size: 25
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    schemas: fee-scheme
    default-schema: fee-scheme
    enabled: true
    locations: classpath:db/migration,classpath:db/repeatable

management:
  server:
    port: 8185
  # specify actuator endpoints to enable
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus

  # show detailed health status
  endpoint:
    health:
      show-details: always


sentry:
  debug: off
  dsn: ${SENTRY_DSN}
  # With a sample rate of 1, all traffic will be sent to Sentry
  traces-sample-rate: 0.50
  environment: ${HOST_ENV}
  release: 1.0.0
  servername: aws-eks-container
  send-default-pii: true
  attach-stacktrace: true
  # With a sample rate of 1, all traffic will be sent to Sentry
  sample-rate: 0.80
  logging:
    minimum-event-level: warn
    minimum-breadcrumb-level: info
  in-app-includes: uk.gov.justice.laa.fee.scheme
