server:
  port: 8085

spring:
  application:
    name: LAA Fee Scheme API

  datasource:
    url: 'jdbc:postgresql://${DB_SERVER}/${DB_NAME}'
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      pool-name: fee-scheme-DB-CP
      connection-timeout: 1000
      validation-timeout: 500
      maximum-pool-size: 25
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: fee_scheme
  flyway:
    schemas: fee_scheme
    default-schema: fee_scheme
    enabled: true
    locations: classpath:db/migration,classpath:db/repeatable

management:
  server:
    port: 8185
  # specify actuator endpoints to enable
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus

  # show detailed health status
  endpoint:
    health:
      show-details: always
