server:
  port: 8085

spring:
  application:
    name: LAA Fee Scheme API


  datasource:
    url: 'jdbc:postgresql://${DB_SERVER}/${DB_NAME}'
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  flyway:
    enabled: false
    locations: classpath:db/migration,classpath:db/repeatable

  #do not auto create db schema, use .sql scripts
  jpa:
    hibernate:
      ddl-auto: none

# used by actuator info endpoint
info:
  app:
    name: LAA Fee Scheme API
    description: LAA Fee Scheme API to calculate fees for a claim and return response to Claim & Assess API.
    version: 1.0.0

management:
  # specify actuator endpoints to enable
  endpoints:
    web:
      exposure:
        include: health

  # show detailed health status
  endpoint:
    health:
      show-details: always
