spring:
  application:
    name: LAA Fee Scheme API

  datasource:
   ## url: jdbc:postgresql://localhost:5432/db5237d17910a637aa
    url: jdbc:postgresql://cloud-platform-5237d17910a637aa.cdwm328dlye6.eu-west-2.rds.amazonaws.com:5432/db5237d17910a637aa
    username: cpnkr95Y3Y
    password: QwaqwkiWndInb9EK
  flyway:
    enabled: true
    locations: classpath:db/migration,classpath:db/repeatable

  #do not auto create db schema, use .sql scripts
  jpa:
    hibernate:
      ddl-auto: none

# used by actuator info endpoint
info:
  app:
    name: LAA Fee Scheme API
    description: LAA Fee Scheme API to calculate fees for a claim and return response to Claim & Assess API.
    version: 1.0.0

management:
  # specify actuator endpoints to enable
  endpoints:
    web:
      exposure:
        include: health,info

  # show detailed health status
  endpoint:
    health:
      show-details: always

  info:
    env:
      enabled: true