spring:
  datasource:
    url: jdbc:h2:mem:feesDb;MODE=PostgreSQL;
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: true

  # do not auto create db schema, use .sql scripts for embedded H2 database
  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    locations: classpath:db/migration