INSERT INTO fee_information (fee_code, fee_description, fee_type)
VALUES ('IACA', 'Standard Fee - Asylum CLR  (2a)', 'FIXED'),
       ('IACB', 'Standard Fee - Asylum CLR (2b + advocacy substantive hearing fee) ', 'FIXED'),
       ('IACC', 'Standard Fee - Asylum CLR (2c + advocacy substantive hearing fee) ', 'FIXED'),
       ('IACE', 'Standard Fee - Asylum CLR 2d ', 'FIXED'),
       ('IACF', 'Standard Fee - Asylum CLR (2e + advocacy substantive hearing fee)  ', 'FIXED'),
       ('IALB', 'Standard Fee - Asylum LH ', 'FIXED'),
       ('IMCA', 'Standard Fee - Immigration CLR (2a)', 'FIXED'),
       ('IMCB', 'Standard Fee - Immigration CLR (2b + advocacy substantive hearing fee) ', 'FIXED'),
       ('IMCC', 'Standard Fee - Immigration CLR (2c + advocacy substantive hearing fee)  ', 'FIXED'),
       ('IMCE', 'Standard Fee - Immigration CLR 2d ', 'FIXED'),
       ('IMCF', 'Standard Fee - Immigration CLR (2e + advocacy substantive hearing fee) ', 'FIXED'),
       ('IMLB', 'Standard Fee - Immigration LH ', 'FIXED'),
       ('IDAS1', 'Detained Duty Advice Scheme (1-4 clients seen)', 'FIXED'),
       ('IDAS2', 'Detained Duty Advice Scheme (5+ clients seen)', 'FIXED'),
       ('IAXL', 'LH Hourly Rates - Asylum - £800 PC and £400 disb', 'HOURLY'),
       ('IMXL', 'LH Hourly Rates - Imm - £500 PC and £400 disb', 'HOURLY'),
       ('IA100', 'LH Hourly Rates  - £100 total limit', 'HOURLY'),
       ('IAXC', 'CLR Hourly Rates Asylum - £1600 total limit', 'HOURLY'),
       ('IMXC', 'CLR Hourly Rates Imm - £1200 total limit', 'HOURLY'),
       ('IRAR', 'CLR Upper Tribunal Transitional cases', 'HOURLY'),
       ('IACD', 'Interim hourly rates - Asylum CLR', 'HOURLY'),
       ('IMCD', 'Interim hourly rates - Immigration Interim CLR', 'HOURLY'),
       ('ICASD', 'Asylum CLR Hourly Rates Stage Disbursement', 'DISB_ONLY'),
       ('ICISD', 'Immigration CLR Hourly Rates Stage Disbursement', 'DISB_ONLY'),
       ('ICSSD', 'CLR SFS Stage Disbursement', 'DISB_ONLY'),
       ('ILHSD', 'LH Stage Disbursement', 'DISB_ONLY')
    ON CONFLICT (fee_code) DO NOTHING;

INSERT INTO fee_information (fee_code, fee_description, fee_type)
VALUES ('MHL01', 'Non-Mental Health Tribunal Fee', 'FIXED'),
       ('MHL02', 'Mental Health Tribunal Fee - Level 1 only', 'FIXED'),
       ('MHL03', 'Mental Health Tribunal Fee - Levels 1 and 2', 'FIXED'),
       ('MHL04', 'Mental Health Tribunal Fee - Levels 1, 2 and 3', 'FIXED'),
       ('MHL05', 'Mental Health Tribunal Fee - Level 2 only', 'FIXED'),
       ('MHL06', 'Mental Health Tribunal Fee - Levels 2 and 3', 'FIXED'),
       ('MHL07', 'Mental Health Tribunal Fee - Level 3 only', 'FIXED'),
       ('MHL08', 'Mental Health Tribunal Fee - Levels 1 and 3', 'FIXED'),
       ('MHL10', 'Mental Health Tribunal Fee - Level 1 (Rule 11(7)(a) cases where a patient has not engaged with the provider)','FIXED'),
       ('MHLDIS', 'Mental Health - Interim Claim for Disbursements', 'DISB_ONLY')
    ON CONFLICT (fee_code) DO NOTHING;

INSERT INTO fee_information (fee_code, fee_description, fee_type)
VALUES ('FPB010', 'Public Family LH Fixed Fee', 'FIXED'),
       ('FPB020', 'Public Family FH Fixed Fee (Section 31 Pre-proceedings Only)', 'FIXED'),
       ('FPB030', 'Public Family LH+FH (Public Family Help Lower can be claimed for Section 31 Pre-proceedings Only)', 'FIXED'),
       ('FVP100', 'Private Family LH Fixed Fee - Divorce Petitioner Only', 'FIXED'),
       ('FVP012', 'Private Family LH Fixed Fee - Divorce Respondent Only', 'FIXED'),
       ('FVP011', 'Private Family LH Fixed Fee - Domestic Abuse Proceedings', 'FIXED'),
       ('FVP013', 'Private Family LH Fixed Fee - Child Abduction (International)', 'FIXED'),
       ('FVP010', 'Private Family LH Fixed Fee - Children or Finance', 'FIXED'),
       ('FVP110', 'Private Family FH Fixed Fee - Children (settled)', 'FIXED'),
       ('FVP130', 'Private Family FH Fixed Fee - Children (not settled)', 'FIXED'),
       ('FVP120', 'Private Family FH Fixed Fee - Finance  (settled)', 'FIXED'),
       ('FVP140', 'Private Family FH Fixed Fee - Finance  (not settled)', 'FIXED'),
       ('FVP150', 'Private Family FH Fixed Fee - Children & Finance (both settled)', 'FIXED'),
       ('FVP180', 'Private Family FH Fixed Fee - Children & Finance  (neither settled)', 'FIXED'),
       ('FVP160', 'Private Family FH Fixed Fee - Children & Finance (children settled)', 'FIXED'),
       ('FVP170', 'Private Family FH Fixed Fee - Children & Finance (finance settled)', 'FIXED'),
       ('FVP190', 'Help with Mediation - Advice Only', 'FIXED'),
       ('FVP200', 'Help with Mediation - Finance Consent Order Only', 'FIXED'),
       ('FVP210', 'Help with Mediation - Advice & Finance Consent Order', 'FIXED')
    ON CONFLICT (fee_code) DO NOTHING;

INSERT INTO fee_information (fee_code, fee_description, fee_type)
VALUES ('FVP020', 'Private Family LH Fixed Fee (Children or Finance) + FH Fixed Fee - Children (settled)', 'FIXED'),
       ('FVP040', 'Private Family LH Fixed Fee (Children or Finance) + FH Fixed Fee - Children (not settled)', 'FIXED'),
       ('FVP030', 'Private Family LH Fixed Fee (Children or Finance) + FH Fixed Fee - Finance (settled)', 'FIXED'),
       ('FVP050', 'Private Family LH Fixed Fee (Children or Finance) + FH Fixed Fee - Finance (not settled)', 'FIXED'),
       ('FVP060', 'Private Family LH Fixed Fee (Children or Finance) + FH Fixed Fee - Children & Finance (both settled)', 'FIXED'),
       ('FVP090', 'Private Family LH Fixed Fee (Children or Finance) + FH Fixed Fee - Children & Finance (neither settled)','FIXED'),
       ('FVP070', 'Private Family LH Fixed Fee (Children or Finance) + FH Fixed Fee - Children & Finance (children settled)','FIXED'),
       ('FVP080', 'Private Family LH Fixed Fee (Children or Finance) + FH Fixed Fee - Children & Finance (finance settled)','FIXED'),
       ('FVP021', 'Private Family LH Fixed Fee (DA Proceedings) + FH Fixed Fee - Children (settled)', 'FIXED'),
       ('FVP041', 'Private Family LH Fixed Fee (DA Proceedings) + FH Fixed Fee - Children (not settled)', 'FIXED'),
       ('FVP031', 'Private Family LH Fixed Fee (DA Proceedings) + FH Fixed Fee - Finance (settled)', 'FIXED'),
       ('FVP051', 'Private Family LH Fixed Fee (DA Proceedings) + FH Fixed Fee - Finance (not settled)', 'FIXED'),
       ('FVP061', 'Private Family LH Fixed Fee (DA Proceedings) + FH Fixed Fee - Children & Finance (both settled)', 'FIXED'),
       ('FVP091', 'Private Family LH Fixed Fee (DA Proceedings) + FH Fixed Fee - Children & Finance (neither settled)', 'FIXED'),
       ('FVP071', 'Private Family LH Fixed Fee (DA Proceedings) + FH Fixed Fee - Children & Finance (children settled)', 'FIXED'),
       ('FVP081', 'Private Family LH Fixed Fee (DA Proceedings) + FH Fixed Fee - Children & Finance (finance settled)', 'FIXED')
    ON CONFLICT (fee_code) DO NOTHING;

INSERT INTO fee_information (fee_code, fee_description, fee_type)
VALUES ('ASSA', 'Mediation Assesment (alone)', 'FIXED'),
       ('ASSS', 'Mediation Assesment (separate)', 'FIXED'),
       ('ASST', 'Mediation Assesment (together)', 'FIXED'),
       ('MDAS2B', 'All Issues Sole -  2 parties eligible, no agreement', 'FIXED'),
       ('MDAS1B', 'All Issues Sole - 1 party eligible, no agreement', 'FIXED'),
       ('MDAC2B', 'All Issues Co - 2 parties eligible, no agreement', 'FIXED'),
       ('MDAC1B', 'All Issues Co -1 party eligible, no agreement', 'FIXED'),
       ('MDAS2S', 'All Issues Sole -  2 parties eligible, agreement on all Issues', 'FIXED'),
       ('MDAS1S', 'All Issues Sole -  1 party eligible, agreement on all Issues', 'FIXED'),
       ('MDAS2P', 'All Issues Sole - 2 parties eligible, agreement on P&F only', 'FIXED'),
       ('MDAS1P', 'All Issues Sole -  1 party eligible, agreement on P&F only', 'FIXED'),
       ('MDAS2C', 'All Issues Sole - 2 parties eligible, agreement on Child only ', 'FIXED'),
       ('MDAS1C', 'All Issues Sole - 1 party eligible, agreement on Child only ', 'FIXED'),
       ('MDAC2S', 'All Issues Co-Mediation -  2 parties eligible, agreement on all Issues', 'FIXED'),
       ('MDAC1S', 'All Issues Co-mediation -  1 party eligible, agreement on all Issues', 'FIXED'),
       ('MDAC2P', 'All Issues Co-mediation - 2 parties eligible, agreement on P&F only', 'FIXED'),
       ('MDAC1P', 'All Issues Co-mediation - 1 party eligible, agreement on P&F only', 'FIXED'),
       ('MDAC2C', 'All Issues Co-mediation - 2 parties eligible, agreement on Child only ', 'FIXED'),
       ('MDAC1C', 'All Issues Co-mediation -  1 party eligible, agreement on Child only ', 'FIXED')
    ON CONFLICT (fee_code) DO NOTHING;

INSERT INTO fee_information (fee_code, fee_description, fee_type)
VALUES ('MDPS2B', 'Property & Finance Sole -  2 parties eligible, no agreement', 'FIXED'),
       ('MDPS1B', 'Property & Finance Sole -  1 party eligible, no agreement', 'FIXED'),
       ('MDPC2B', 'Property & Finance Co - 2 parties eligible, no agreement', 'FIXED'),
       ('MDPC1B', 'Property & Finance Co - 1 party eligible, no agreement', 'FIXED'),
       ('MDPS2S', 'Property & Finance Sole -  2 parties eligible, with agreed proposal', 'FIXED'),
       ('MDPS1S', 'Property & Finance Sole -1 party eligible, with agreed proposal', 'FIXED'),
       ('MDPC2S', 'Property & Finance Co -  2 parties eligible, with agreed proposal', 'FIXED'),
       ('MDPC1S', 'Property & Finance Co -  1 party eligible, with agreed proposal', 'FIXED'),
       ('MDCS2B', 'Child only Sole -2 parties eligible, no agreement', 'FIXED'),
       ('MDCS1B', 'Child only Sole - 1 party eligible, no agreement', 'FIXED'),
       ('MDCC2B', 'Child only Co - 2 parties eligible, no agreement', 'FIXED'),
       ('MDCC1B', 'Child only Co -  1 party eligible, no agreement', 'FIXED'),
       ('MDCS2S', 'Child only Sole - 2 parties eligible, with agreed proposal', 'FIXED'),
       ('MDCS1S', 'Child only Sole - 1 party eligible, with agreed proposal', 'FIXED'),
       ('MDCC2S', 'Child only Co - 2 parties eligible, with agreed proposal', 'FIXED'),
       ('MDCC1S', 'Child only Co - 1 party eligible, with agreed proposal', 'FIXED')
    ON CONFLICT (fee_code) DO NOTHING;

INSERT INTO fee_information (fee_code, fee_description, fee_type)
VALUES ('COM', 'Community Care Legal Help Fixed Fee', 'FIXED'),
       ('CAPA', 'Claims Against Public Authorities Legal Help Fixed Fee', 'FIXED'),
       ('CLIN', 'Clinical Negligence Legal Help Fixed Fee', 'FIXED'),
       ('DEBT', 'Debt Legal Help Fixed Fee', 'FIXED'),
       ('DISC', 'Discrimination Legal Help Payment', 'HOURLY'),
       ('EDUFIN', 'Education Legal Help Fixed Fee', 'FIXED'),
       ('EDUDIS', 'Education - Interim Claim for Disbursement', 'DISB_ONLY'),
       ('ELA', 'HLPAS Stage One: early legal advice', 'FIXED'),
       ('HOUS', 'Housing Fixed Fee', 'FIXED'),
       ('MISCGEN', 'Miscellaneous Legal Help Fixed Fee', 'FIXED'),
       ('MISCCON', 'Miscellaneous (Consumer) Legal Help Fixed Fee', 'FIXED'),
       ('MISCPI', 'Miscellaneous (Personal Injury) Legal Help Fixed Fee', 'FIXED'),
       ('MISCASBI', 'Miscellaneous (ASBI) Legal Help Fixed Fee', 'FIXED'),
       ('MISCEMP', 'Miscellaneous (Employment) Legal Help Fixed Fee', 'FIXED'),
       ('PUB', 'Public Law Legal Help Fixed Fee', 'FIXED'),
       ('WFB1', 'Welfare Benefits Controlled Work fee', 'FIXED')
    ON CONFLICT (fee_code) DO NOTHING;

INSERT INTO fee_information (fee_code, fee_description, fee_type)
VALUES ('INVC', 'Police station: attendance', 'FIXED'),
       ('INVA', 'Advice and Assistance (not at the police station)', 'HOURLY'),
       ('INVE', 'Warrant of further detention (including armed forces, Terrorism Act 2000, advice & assistance and other police station advice where given)','HOURLY'),
       ('INVH', 'Police Station: Post-charge attendance', 'HOURLY'),
       ('INVK', 'Advocacy Assistance in the magistrates’ court on applications to extend Pre-Charge Bail (Extension to Pre-Charge Bail)','HOURLY'),
       ('INVL', 'Advocacy Assistance in the magistrates’ court on application to vary Pre-Charge Bail conditions (Varying Pre-Charge Bail)','HOURLY'),
       ('INVM', 'Pre-Charge Engagement Advice and Assistance ', 'HOURLY'),
       ('INVB1', 'Police station: telephone advice only (London)', 'FIXED'),
       ('INVB2', 'Police station: telephone advice only (Outside of London)', 'FIXED'),
       ('PROE1', 'Representation in the Magistrates Court - category 1A -  lower standard fee - undesignated area', 'FIXED'),
       ('PROE2', 'Representation in the Magistrates Court - category 1B -  lower standard fee  - undesignated area', 'FIXED'),
       ('PROE3', 'Representation in the Magistrates Court - category 2 -  lower standard fee - undesignated area', 'FIXED'),
       ('PROF1', 'Representation in the Magistrates Court - category 1A -  higher standard fee - undesignated area', 'FIXED'),
       ('PROF2', 'Representation in the Magistrates Court - category 1B -  higher standard fee - undesignated area', 'FIXED'),
       ('PROF3', 'Representation in the Magistrates Court - category 2 -  higher standard fee - undesignated area', 'FIXED'),
       ('PROJ1', 'Representation in the Magistrates Court - second claim for deferred sentence - category 1A -  lower standard fee - undesignated area','FIXED'),
       ('PROJ2', 'Representation in the Magistrates Court - second claim for deferred sentence - category 1B -  lower standard fee - undesignated area','FIXED'),
       ('PROJ3', 'Representation in the Magistrates Court - second claim for deferred sentence -  category 1A -  higher standard fee - undesignated area','FIXED'),
       ('PROJ4', 'Representation in the Magistrates Court - second claim for deferred sentence - category 1B -  higher standard fee - undesignated area','FIXED'),
       ('PROJ5', 'Representation in the Magistrates Court - second claim for deferred sentence - category 1A - lower standard fee - designated area','FIXED'),
       ('PROJ6', 'Representation in the Magistrates Court - second claim for deferred sentence - category 1B - lower standard fee - designated area','FIXED'),
       ('PROJ7', 'Representation in the Magistrates Court - second claim for deferred sentence - category 1A -  higher standard fee - designated area','FIXED'),
       ('PROJ8', 'Representation in the Magistrates Court - second claim for deferred sentence - category 1B -  higher standard fee - designated area','FIXED'),
       ('PROK1', 'Representation in the Magistrates Court - category 1A - lower standard fee - designated area', 'FIXED'),
       ('PROK2', 'Representation in the Magistrates Court - category 1B - lower standard fee - designated area', 'FIXED'),
       ('PROK3', 'Representation in the Magistrates Court - category 2 - lower standard fee - designated area', 'FIXED')
    ON CONFLICT (fee_code) DO NOTHING;

INSERT INTO fee_information (fee_code, fee_description, fee_type)
VALUES ('PROL1', 'Representation in the Magistrates Court - category 1A -  higher standard fee - designated area', 'FIXED'),
       ('PROL2', 'Representation in the Magistrates Court - category 1B -  higher standard fee - designated area', 'FIXED'),
       ('PROL3', 'Representation in the Magistrates Court - category 2 -  higher standard fee - designated area','FIXED'),
       ('PROV1', 'Breach of part 1 injunctions under ASBCP Act - uncontested - lower standard fee', 'FIXED'),
       ('PROV2', 'Breach of part 1 injunctions under ASBCP Act - uncontested - higher standard fee', 'FIXED'),
       ('PROV3', 'Breach of part 1 injunctions under ASBCP Act - contested - lower standard fee', 'FIXED'),
       ('PROV4', 'Breach of part 1 injunctions under ASBCP Act - contested - higher standard fee', 'FIXED'),
       ('PROT', 'Early Cover', 'FIXED'),
       ('PROU', 'Refused means test – form completion fee', 'FIXED'),
       ('PROW', 'Sending Hearing Fixed Fee ', 'FIXED'),
       ('PROD', 'Advice and Assistance and Advocacy Assistance by a court Duty Solicitor', 'FIXED'),
       ('PROP1', 'Pre Order Cover - London', 'FIXED'),
       ('PROP2', 'Pre Order Cover - National', 'FIXED'),
       ('PROH', 'Advocacy Assistance in the Crown Court', 'FIXED'),
       ('YOUE1', 'Youth Representation Order - category 1A - lower standard fee - undesignated area', 'FIXED'),
       ('YOUE2', 'Youth Representation Order - category 1B - lower standard fee - undesignated area', 'FIXED'),
       ('YOUE3', 'Youth Representation Order - category 2A - lower standard fee - undesignated area', 'FIXED'),
       ('YOUE4', 'Youth Representation Order - category 2B - lower standard fee - undesignated area', 'FIXED'),
       ('YOUF1', 'Youth Representation Order - category 1A - higher standard fee - undesignated area', 'FIXED'),
       ('YOUF2', 'Youth Representation Order - category 1B - higher standard fee - undesignated area', 'FIXED'),
       ('YOUF3', 'Youth Representation Order - category 2A - higher standard fee - undesignated area', 'FIXED'),
       ('YOUF4', 'Youth Representation Order - category 2B - higher standard fee - undesignated area', 'FIXED'),
       ('YOUK1', 'Youth Representation Order - category 1A - lower standard fee - designated area', 'FIXED'),
       ('YOUK2', 'Youth Representation Order - category 1B - lower standard fee - designated area', 'FIXED'),
       ('YOUK3', 'Youth Representation Order - category 2A - lower standard fee - designated area', 'FIXED'),
       ('YOUK4', 'Youth Representation Order - category 2B - lower standard fee - designated area', 'FIXED'),
       ('YOUL1', 'Youth Representation Order - category 1A - higher standard fee - designated area', 'FIXED'),
       ('YOUL2', 'Youth Representation Order - category 1B - higher standard fee - designated area', 'FIXED'),
       ('YOUL3', 'Youth Representation Order - category 2A - higher standard fee - designated area', 'FIXED'),
       ('YOUL4', 'Youth Representation Order - category 2B - higher standard fee - designated area', 'FIXED'),
       ('YOUX1', 'Youth Representation Order - second claim for deferred sentence - category 1A - lower standard fee - undesignated area','FIXED'),
       ('YOUX2', 'Youth Representation Order - second claim for deferred sentence - category 1B - lower standard fee - undesignated area','FIXED')
    ON CONFLICT (fee_code) DO NOTHING;

INSERT INTO fee_information (fee_code, fee_description, fee_type)
VALUES ('YOUX3','Youth Representation Order - second claim for deferred sentence - category 1A - higher standard fee - undesignated area','FIXED'),
       ('YOUX4','Youth Representation Order - second claim for deferred sentence - category 1B - higher standard fee - undesignated area','FIXED'),
       ('YOUY1','Youth Representation Order - second claim for deferred sentence - category 1A - lower standard fee - designated area','FIXED'),
       ('YOUY2','Youth Representation Order - second claim for deferred sentence - category 1B - lower standard fee - designated area','FIXED'),
       ('YOUY3','Youth Representation Order - second claim for deferred sentence - category 1A - higher standard fee - designated area','FIXED'),
       ('YOUY4','Youth Representation Order - second claim for deferred sentence - category 1B - higher standard fee - designated area','FIXED')
    ON CONFLICT (fee_code) DO NOTHING;

INSERT INTO fee_information (fee_code, fee_description, fee_type)
VALUES ('PRIA', 'Free Standing Advice and Assistance', 'FIXED'),
       ('PRIB1', 'Disciplinary Cases – Advocacy Assistance - lower standard fee', 'FIXED'),
       ('PRIB2', 'Disciplinary Cases – Advocacy Assistance - higher standard fee', 'FIXED'),
       ('PRIC1', 'Parole Board Cases – Advocacy Assistance - lower standard fee', 'FIXED'),
       ('PRIC2', 'Parole Board Cases – Advocacy Assistance - higher standard fee', 'FIXED'),
       ('PRID1', 'Advocacy Assistance at Sentence Reviews - lower standard fee', 'FIXED'),
       ('PRID2', 'Advocacy Assistance at Sentence Reviews - higher standard fee', 'FIXED'),
       ('PRIE1', 'Advocacy Assistance at Parole Board Reconsideration Hearings - lower standard fee', 'FIXED'),
       ('PRIE2', 'Advocacy Assistance at Parole Board Reconsideration Hearings - higher standard fee', 'FIXED'),
       ('APPA', 'Advice and assistance in relation to an appeal (except CCRC)', 'FIXED'),
       ('APPB', 'Advice and assistance in relation to CCRC application', 'FIXED'),
       ('ASMS', 'Legal Help and Associated Civil Work – Miscellaneous', 'FIXED'),
       ('ASPL', 'Legal Help and Associated Civil Work – Public Law', 'FIXED'),
       ('ASAS', 'Part 1 injunction Anti-Social Behaviour Crime and Policing Act 2014', 'FIXED')
    ON CONFLICT (fee_code) DO NOTHING;
