INSERT INTO fee (fee_code,fee_scheme_code,total_fee,profit_cost_limit,disbursement_limit,escape_threshold_limit,prior_authority_applicable,schedule_reference,ho_interview_bolt_on,oral_cmrh_bolt_on,telephone_cmrh_bolt_on,substantive_hearing_bolt_on,adjorn_hearing_bolt_on,mediation_session_one,mediation_session_two,region,description) VALUES
                                                                                                                                                                                                                                                                                                                                                   ('INVA','POL_FS2016',NULL,273.75,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Advice and Assistance (not at the police station)'),
                                                                                                                                                                                                                                                                                                                                                   ('INVE','POL_FS2016',NULL,1368.75,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Warrant of further detention (including Terrorism Act 2000, advice & assistance and other police station advice where given)'),
                                                                                                                                                                                                                                                                                                                                                   ('INVF','POL_FS2016',NULL,1368.75,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Warrant of further detention (armed forces) (including Terrorism Act 2000, advice & assistance and other police station advice where given)'),
                                                                                                                                                                                                                                                                                                                                                   ('INVH','POL_FS2016',NULL,1368.75,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Police Station: Post-charge attendance – breach of bail/arrest on warrant'),
                                                                                                                                                                                                                                                                                                                                                   ('INVK','POL_FS2016',NULL,1368.75,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Advocacy Assistance in the magistrates’ court on applications to extend Pre-Charge Bail (Extension to Pre-Charge Bail)'),
                                                                                                                                                                                                                                                                                                                                                   ('INVL','POL_FS2016',NULL,1368.75,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Advocacy Assistance in the magistrates’ court on application to vary Pre-Charge Bail conditions (Varying Pre-Charge Bail)'),
                                                                                                                                                                                                                                                                                                                                                   ('INVI','POL_FS2016',NULL,1368.75,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Police Station: Post-charge attendance - Post-charge identification procedure/ recharge/ referral back for caution,  reprimand, warning'),
                                                                                                                                                                                                                                                                                                                                                   ('INVA','POL_FS2022',NULL,314.81,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Advice and Assistance (not at the police station)'),
                                                                                                                                                                                                                                                                                                                                                   ('INVE','POL_FS2022',NULL,1574.06,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Warrant of further detention (including Terrorism Act 2000, advice & assistance and other police station advice where given)'),
                                                                                                                                                                                                                                                                                                                                                   ('INVF','POL_FS2022',NULL,1574.06,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Warrant of further detention (armed forces) (including Terrorism Act 2000, advice & assistance and other police station advice where given)');
INSERT INTO fee (fee_code,fee_scheme_code,total_fee,profit_cost_limit,disbursement_limit,escape_threshold_limit,prior_authority_applicable,schedule_reference,ho_interview_bolt_on,oral_cmrh_bolt_on,telephone_cmrh_bolt_on,substantive_hearing_bolt_on,adjorn_hearing_bolt_on,mediation_session_one,mediation_session_two,region,description) VALUES
                                                                                                                                                                                                                                                                                                                                                   ('INVH','POL_FS2022',NULL,1574.06,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Police Station: Post-charge attendance – breach of bail/arrest on warrant'),
                                                                                                                                                                                                                                                                                                                                                   ('INVK','POL_FS2022',NULL,1574.06,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Advocacy Assistance in the magistrates’ court on applications to extend Pre-Charge Bail (Extension to Pre-Charge Bail)'),
                                                                                                                                                                                                                                                                                                                                                   ('INVL','POL_FS2022',NULL,1574.06,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Advocacy Assistance in the magistrates’ court on application to vary Pre-Charge Bail conditions (Varying Pre-Charge Bail)'),
                                                                                                                                                                                                                                                                                                                                                   ('INVI','POL_FS2022',NULL,1574.06,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Police Station: Post-charge attendance - Post-charge identification procedure/ recharge/ referral back for caution,  reprimand, warning'),
                                                                                                                                                                                                                                                                                                                                                   ('INVM','POL_FS2021',NULL,273.75,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Pre-Charge Engagement Advice and Assistance UFN Date (for case starting from 07/06/2021)'),
                                                                                                                                                                                                                                                                                                                                                   ('INVB1','POL_FS2016',NULL,28.70,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Police station: telephone advice only (London)'),
                                                                                                                                                                                                                                                                                                                                                   ('INVB2','POL_FS2016',NULL,27.60,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Police station: telephone advice only (Outside of London)'),
                                                                                                                                                                                                                                                                                                                                                   ('INVC','POL_FS2016',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Police station: attendance'),
                                                                                                                                                                                                                                                                                                                                                   ('INVD','POL_FS2016',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Police station: attendance (armed forces)'),
                                                                                                                                                                                                                                                                                                                                                   ('INVJ','POL_FS2016',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Police station attendance: Immigration matter');
INSERT INTO fee (fee_code,fee_scheme_code,total_fee,profit_cost_limit,disbursement_limit,escape_threshold_limit,prior_authority_applicable,schedule_reference,ho_interview_bolt_on,oral_cmrh_bolt_on,telephone_cmrh_bolt_on,substantive_hearing_bolt_on,adjorn_hearing_bolt_on,mediation_session_one,mediation_session_two,region,description) VALUES
                                                                                                                                                                                                                                                                                                                                                   ('INVB1','POL_FS2022',NULL,33.00,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Police station: telephone advice only (London)'),
                                                                                                                                                                                                                                                                                                                                                   ('INVB2','POL_FS2022',NULL,31.74,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Police station: telephone advice only (Outside of London)'),
                                                                                                                                                                                                                                                                                                                                                   ('INVC','POL_FS2022',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Police station: attendance'),
                                                                                                                                                                                                                                                                                                                                                   ('INVD','POL_FS2022',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Police station: attendance (armed forces)'),
                                                                                                                                                                                                                                                                                                                                                   ('INVJ','POL_FS2022',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Police station attendance: Immigration matter');
