-- COPY police_station_fees (    police_station_fees_id,
--                               criminal_justice_area,
--                               police_station_name,
--                               police_station_code,
--                               fixed_fee,
--                               escape_threshold,
--                               fee_scheme_code)
--     FROM '/db/csv/police_station_fees.csv'
--     DELIMITER ','
--     CSV HEADER;
