package uk.gov.justice.laa.fee.scheme.feecalculator;

/**
 * enum for the types of calculations.
 */
public enum CalculationType {

  CLAIMS_PUBLIC_AUTHORITIES,
  CLINICAL_NEGLIGENCE,
  COMMUNITY_CARE,
  DEBT,
  DISCRIMINATION,
  HOUSING,
  HOUSING_HLPAS,
  IMMIGRATION_ASYLUM_FIXED_FEE,
  IMMIGRATION_ASYLUM_HOURLY_RATE,
  MEDIATION,
  MENTAL_HEALTH,
  MISCELLANEOUS,
  POLICE_STATION,
  PUBLIC_LAW,
  WELFARE_BENEFITS

}
