apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Chart.Name }}-monitoring
  labels:
    {{- include "laa-fee-scheme-api.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "laa-fee-scheme-api.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              component: monitoring
