apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-service"
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "laa-fee-scheme-api.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
    - name: actuator
      port: {{ .Values.actuator.port }}
      targetPort: actuator
      protocol: TCP
  selector:
    {{ include "laa-fee-scheme-api.selectorLabels" . | nindent 4 }}
