apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Chart.Name }}-monitoring
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{- include "laa-fee-scheme-api.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: actuator
      interval: {{ .Values.actuator.metrics.scrapeInterval }}
      path: {{ .Values.actuator.metrics.path }}
