apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-service"
  namespace: "{{ .Chart.Name }}-{{ .Values.service.environment }}"
  labels:
    {{- include "laa-fee-scheme-api.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "laa-fee-scheme-api.selectorLabels" . | nindent 4 }}
