name: PR build and test
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  pull-requests: write
  issues: write
  security-events: read

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v6

      - name: Build and run tests
        uses: './.github/actions/build-and-test'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  snyk-vulnerability-scan:
    permissions:
      contents: read
      security-events: write
    uses: ./.github/workflows/snyk-vulnerability-scans.yml
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      SLACK_PROD_WEBHOOK_URL: ${{ secrets.SLACK_PROD_WEBHOOK_URL }}

  zap-pr-scan:
    permissions:
      contents: read
      security-events: write
    uses: ./.github/workflows/zap-security-scan.yml
    secrets:
      SLACK_PROD_WEBHOOK_URL: ${{ secrets.SLACK_PROD_WEBHOOK_URL }}

  sca-pr-scan:
    permissions:
      contents: write
      pull-requests: write
      issues: write
      security-events: read
    uses: ./.github/workflows/sca-analysis.yml