name: Synk weekly security scan
on:
  schedule:
   - cron: '0 8 * * MON'

jobs:
  weekly-snyk-security-scan:
    uses: ./.github/workflows/snyk-vulnerability-scans.yml
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
