name: ZAP PR Scan
on:
  workflow_call:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build API Docker Image
        run: docker build -t myapp:pr-image .

      - name: Start API Container
        run: |
          docker network create zap-net
          docker run -d --name myapp --network zap-net myapp:pr-image
          sleep 30
          docker ps -a

      - name: Run ZAP OpenAPI Scan
        run: |
          docker run --rm \
            --network zap-net \
            -v "${{ github.workspace }}:/zap/wrk" \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-api-scan.py \
              -t http://myapp:8080/v3/api-docs \
              -f openapi \
              -r /zap/wrk/zap-pr-report.html \
              -z >
                -config replacer.full_list(0).description=authheader
                -config replacer.full_list(0).enabled=true
                -config replacer.full_list(0).matchtype=REQ_HEADER
                -config replacer.full_list(0).matchstr=Authorization
                -config replacer.full_list(0).replacement='Bearer 1234'

      - name: Upload ZAP PR Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-pr-report
          path: zap-pr-report.html
