name: ZAP PR Scan
on:
  workflow_call:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build API JAR
        run: ./gradlew clean build

      - name: Build API Docker Image
        run: docker build -t laa-fee-scheme-api:pr-image .

      - name: Start Postgres DB
        run: |
          docker network create zap-net || true
          docker run -d --name fee-scheme-db --network zap-net \
            -e POSTGRES_USER=test \
            -e POSTGRES_PASSWORD=test \
            -e POSTGRES_DB=fee_scheme \
            -p 5432:5432 \
            postgres:15

      - name: Wait for DB
        run: |
          echo "Wait for Postgres"
          until docker exec fee-scheme-db pg_isready -U test > /dev/null; do
            sleep 5
          done
          echo "Postgres ready."

      - name: Start API Container
        run: |
          docker run -d --name laa-fee-scheme-api --network zap-net \
            -e SPRING_DATASOURCE_URL=jdbc:postgresql://fee-scheme-db:5432/fee_scheme \
            -e SPRING_DATASOURCE_USERNAME=test \
            -e SPRING_DATASOURCE_PASSWORD=test \
            -e SPRING_PROFILES_ACTIVE=test \
            -p 8085:8085 -p 8185:8185 \
            laa-fee-scheme-api:pr-image

      - name: Wait for API to be ready
        run: |
          echo "Waiting for API."
          until docker exec laa-fee-scheme-api curl -s http://localhost:8185/actuator/health | grep UP > /dev/null; do
            echo "API not ready yet..."
            sleep 5
          done
          echo "API ready"

      - name: Run ZAP OpenAPI Scan
        run: |
          docker run --rm \
            --network zap-net \
            -v "${{ github.workspace }}:/zap/wrk" \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-api-scan.py \
              -t http://laa-fee-scheme-api:8085/v3/api-docs \
              -f openapi \
              -r /zap/wrk/zap-pr-report.html \
              -z "-config replacer.full_list(0).description=authheader \
                  -config replacer.full_list(0).enabled=true \
                  -config replacer.full_list(0).matchtype=REQ_HEADER \
                  -config replacer.full_list(0).matchstr=Authorization \
                  -config replacer.full_list(0).replacement='Bearer 1234'"

      - name: Upload ZAP PR Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-pr-report
          path: zap-pr-report.html
